### ISSUE TITLE
train_diffusion_model

### ISSUE THREAD

**Issue by ZhengJianwei2** [StanfordMIMI/DDM2#12]
i meet a same problem as a closed issues as follows:
Traceback (most recent call last):
  File "train_diff_model.py", line 54, in <module>
    diffusion = Model.create_model(opt)
  File "/home/star/jiangjiawei/DDM2-main/model/__init__.py", line 7, in create_model
    m = M(opt)
  File "/home/star/jiangjiawei/DDM2-main/model/model.py", line 71, in __init__
    self.load_network()
  File "/home/star/jiangjiawei/DDM2-main/model/model.py", line 223, in load_network
    self.optG.load_state_dict(opt['optimizer'])
  File "/home/star/anaconda3/envs/py37/lib/python3.7/site-packages/torch/optim/optimizer.py", line 201, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

As reminded, i checked the config file path of stage 1 and stage 2， and i think the path setting is correct, are there any other problems may cause this issue? and the details of training logs and the .txt file are also attached. 
![image](https://github.com/StanfordMIMI/DDM2/assets/25289979/edf3b617-a65d-4aa7-b384-77bde80e8daf)
![image](https://github.com/StanfordMIMI/DDM2/assets/25289979/14cc8ff6-ec7f-432a-8474-0d4d06b63f29)
![image](https://github.com/StanfordMIMI/DDM2/assets/25289979/426a7dcf-8bb0-43dc-8249-9ee517a12d5d)

**Comment by ZhengJianwei2** [comment]
I found the problem, in stage3, we need to set the resume _ stage in the path to null
![image](https://github.com/StanfordMIMI/DDM2/assets/25289979/94c49174-021d-40e7-89b0-9058ae71aa70)
