### ISSUE TITLE
Clarifications on dimensions

### ISSUE THREAD

**Issue by anar-rzayev** [StanfordMIMI/DDM2#18]
Hi, thank you for this amazing method. I wanted to ask you very few questions to elaborate in very detail.

I have seen it in multiple places (i.e. `mri_dataset.py`) that you define `valid_mask = [10, 160]`. Considering your data size as (81, 106, 76, 160), are there any particular reasons you choose `val_volume _idx  = 40` and select valid_mask to be [10, 160]? The reason I asked is because I am working with (118, 118, 25, 56) 4D-data and there are some issues I fall into when defining mri_dataset.py as follows: 

```
valid_mask = np.zeros(56,)
valid_mask[10:] += 1
valid_mask = valid_mask.astype(np.bool8)
dataset = MRIDataset("/home/anar/DDM2/data/HARDI150.nii.gz", valid_mask = [10, 56],
                         phase='train', val_volume_idx=40, padding=3)
```

```
Traceback (most recent call last):
  File "/home/anar/DDM2/train_noise_model.py", line 92, in <module>
    for _,  val_data in enumerate(val_loader):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/DDM2/data/mri_dataset.py", line 118, in __getitem__
    raw_input[:,:,slice_idx:slice_idx+2*(self.in_channel//2)+1,[volume_idx+self.padding]]), axis=-1)
IndexError: index 41 is out of bounds for axis 3 with size 8
```

Do you know where did this originate?

**Comment by tiangexiang** [comment]
Hi, thank you for your interest! 

Let me clarify the data dimensions first. Given a 4D MRI data **[W, H, Z, T]**, in which [W, H, Z] are the dimensions to describe the MRI scan in the 3D space representing the length at the three (x,y,z) axes. For a 4D MRI scan with multiple acquisitions, the additional 4th dimension **T** indicates the number of observations of the same 3D structure. Due to the randomness in each acquisition, each 3D observation may be noisy in a different way. Denoising methods (including DDM<sup>2</sup>) are designed to try to learn consistency across those different noisy observations to recover a clean 3D structure.

For the choice of `val_volume _idx  = 40`: this is a random choice. You may choose any volume to validate without affecting the training process. And the choice of`valid_mask = [10, 160]`: this indicates which interval of observations are **NOT** with a b-value = 0. For the hardi150 dataset, the first 10 observations have b-values = 0, therefore we exclude them from the training process and mask them using the `valid_mask = [10, 160]` (meaning using  160-10 observations at the Tdimension).

Back to your problem, I think it still makes sense to set the same parameters for `val_volume _idx` and `valid_mask`. The problem indicates the raw data you loaded seems to only have T=8 observations instead of T=56. I suggest to double check the data first and make sure the loaded raw data has the expected data size.

**Comment by anar-rzayev** [comment]
Thanks so much, Tiange, for your fast response to this issue and detailed explanations on `valid_mask` & `val_volume_idx`. As you instructed, I changed `.json file` and `mri_dataset.py` to have `valid_mask = [20, 56]` to capture non-zero b_val volumes from the dataset. 

Now, after solving a minor bug as in the following,

```
24-01-14 20:28:08.899 - INFO: [Phase 1] Training noise model!
24-01-14 20:28:10.231 - INFO: MRI dataset [hardi] is created.
24-01-14 20:28:13.083 - INFO: MRI dataset [hardi] is created.
24-01-14 20:28:13.083 - INFO: Initial Dataset Finished
24-01-14 20:28:13.463 - INFO: Noise Model is created.
24-01-14 20:28:13.463 - INFO: Initial Model Finished
2.1.2+cu121 12.1
export CUDA_VISIBLE_DEVICES=0
Loaded data of size: (118, 118, 25, 56)
Loaded data of size: (118, 118, 25, 56)
dropout 0.0 encoder dropout 0.0
Traceback (most recent call last):
  File "/home/anar/DDM2/train_noise_model.py", line 72, in <module>
    trainer.optimize_parameters()
  File "/home/anar/DDM2/model/model_stage1.py", line 62, in optimize_parameters
    outputs = self.netG(self.data)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anar/DDM2/model/mri_modules/noise_model.py", line 44, in forward
    return self.p_losses(x, *args, **kwargs)
  File "/home/anar/DDM2/model/mri_modules/noise_model.py", line 36, in p_losses
    x_recon = self.denoise_fn(x_in['condition'])
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anar/DDM2/model/mri_modules/unet.py", line 286, in forward
    x = layer(x)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (double) and bias type (float) should be the same
```

I added a new line `raw_data = raw_data.astype(np.float32)` after loading NIFTI data and then found another unsolvable issue for my case:

```
24-01-14 20:29:55.122 - INFO: [Phase 1] Training noise model!
24-01-14 20:29:56.211 - INFO: MRI dataset [hardi] is created.
24-01-14 20:29:56.892 - INFO: MRI dataset [hardi] is created.
24-01-14 20:29:56.892 - INFO: Initial Dataset Finished
24-01-14 20:29:57.252 - INFO: Noise Model is created.
24-01-14 20:29:57.252 - INFO: Initial Model Finished
24-01-14 20:31:55.243 - INFO: <epoch: 35, iter:   1,000> l_pix: 3.8268e-03 
24-01-14 20:33:51.252 - INFO: <epoch: 69, iter:   2,000> l_pix: 3.1790e-03 
2.1.2+cu121 12.1
export CUDA_VISIBLE_DEVICES=0
Loaded data of size: (118, 118, 25, 56)
Loaded data of size: (118, 118, 25, 56)
dropout 0.0 encoder dropout 0.0
Validation
Traceback (most recent call last):
  File "/home/anar/DDM2/train_noise_model.py", line 92, in <module>
    for _,  val_data in enumerate(val_loader):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/DDM2/data/mri_dataset.py", line 128, in __getitem__
    raw_input = raw_input[:,:,0]
IndexError: index 0 is out of bounds for axis 2 with size 0
```

Do you know how to possibly solve this issue, since I have tried a lot of modifications but neither of them solve this last problem?

**Comment by tiangexiang** [comment]
Hi, it seems the error comes from the shape of the raw_input. Can you make sure the tensor `raw_input` is in the shape **[W, H, -1]**, or **[W, H, 1, -1]** before that line of code?

**Comment by anar-rzayev** [comment]
In order to double check the shapes, I changed the codes to the following:
```
# w, h, c, d = raw_input.shape
# raw_input = np.reshape(raw_input, (w, h, -1))
print("raw_input shape before slicing:", raw_input.shape)
if len(raw_input.shape) == 4:
    raw_input = raw_input[:,:,0]
    print("raw_input shape after slicing:", raw_input.shape)
raw_input = self.transforms(raw_input) # only support the first channel for now
# raw_input = raw_input.view(c, d, w, h)
```

And in the results, I get as follows:

```
raw_input shape before slicing: (118, 118, 1, 3)
raw_input shape after slicing: (118, 118, 3)
Validation
Traceback (most recent call last):
  File "/home/anar/DDM2/train_noise_model.py", line 92, in <module>
    for _,  val_data in enumerate(val_loader):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/DDM2/data/mri_dataset.py", line 129, in __getitem__
    raw_input = raw_input[:,:,0]
IndexError: index 0 is out of bounds for axis 2 with size 0
```

**Comment by tiangexiang** [comment]
it seems that the data loaded for training is good, but the data loaded for validation may not be in the right shape. In any forms, the problem must come from how you load the data. I am not able to provide meaningful suggestions without more information, I still suggest to inspect the tensor shape at all possible locations.

**Comment by anar-rzayev** [comment]
BTW, for the previous issue case, I even added `raw_input = np.reshape(raw_input, (raw_input.shape[0], raw_input.shape[1], 1, -1))` before `raw_input = raw_input[:,:,0]` but still, the following error comes to play

```
raw_input shape before slicing: (118, 118, 1, 3)
raw_input shape after slicing: (118, 118, 3)
Validation
Traceback (most recent call last):
  File "/home/anar/DDM2/train_noise_model.py", line 92, in <module>
    for _,  val_data in enumerate(val_loader):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/miniconda3/envs/ddm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anar/DDM2/data/mri_dataset.py", line 135, in __getitem__
    ret = dict(X=raw_input[[-1], :, :], condition=raw_input[:-1, :, :])
IndexError: index is out of bounds for dimension with size 0
```

**Comment by anar-rzayev** [comment]
This is so weird, how come the training load was successful but validation failed?! My dataset is simply `.nii.gz` file, I combined multiple 3D DWI volumes into one data.
